server:
  slurmdb:
    ClusterName: "test"
    host: "192.168.0.71"
    port: 3306
    user: "slurm"
    password: "123123"
    database: "slurm_acct_db"
    charset: "utf8mb4"
    parseTime: true
    loc: "UTC"
    # tls: "skip-verify"            # "", "true", "skip-verify", "preferred", or custom name
    maxOpenConns: 50
    maxIdleConns: 10
    connMaxLifetime: "1h"

  ldap:
    # Connection/auth used by code
    host: "192.168.0.1"
    port: 30389
    useTLS: false           # url 为 ldap://，因此不启用 TLS
    startTLS: false
    insecureSkipVerify: false
    serverName: ""
    rootCAFile: ""
    clientCertFile: ""
    clientKeyFile: ""

    bindDN: "cn=admin,dc=dc-test,dc=cn"
    bindPassword: "adminpassword"
    baseDN: "dc=dc-test,dc=cn"

    connectTimeout: "5s"
    readTimeout: "10s"
